GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text":"Watch Anime"
}

###

DELETE http://localhost:3001/todo/delete/628b56aa0e3f7538b16c8 

###

PUT http://localhost:3001/todo/complete/628b6e34a6476f11084a1b0e