GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text":"Watch Anime"
}

###

DELETE http://localhost:3001/todo/delete/628bc0da2e2476e5f3331ef7

###

PUT http://localhost:3001/todo/complete/628b6e34a6476f11084a1b0e